import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:flutter/services.dart';

import '../data/computer_sales_models.dart';

class ComputerDocumentService {
  const ComputerDocumentService._();

  static Future<void> printDocument(
    ComputerDocument document, {
    required String businessName,
  }) async {
    final bytes = await buildPdf(document, businessName: businessName);
    await Printing.layoutPdf(onLayout: (_) async => bytes);
  }

  static Future<void> shareDocument(
    ComputerDocument document, {
    required String businessName,
  }) async {
    final bytes = await buildPdf(document, businessName: businessName);
    await Printing.sharePdf(
      bytes: bytes,
      filename: '${document.documentNumber}.pdf',
    );
  }

  static Future<Uint8List> buildPdf(
    ComputerDocument document, {
    required String businessName,
  }) async {
    final regularFont = pw.Font.ttf(
      await rootBundle.load('assets/fonts/Amiri-Regular.ttf'),
    );
    final boldFont = pw.Font.ttf(
      await rootBundle.load('assets/fonts/Amiri-Bold.ttf'),
    );
    final pdf = pw.Document(
      title: document.documentNumber,
      author: businessName,
      subject: '${document.type.label} for ${document.customerName}',
      theme: pw.ThemeData.withFont(base: regularFont, bold: boldFont),
    );
    String money(double value) => 'EGP ${value.toStringAsFixed(2)}';
    final date = DateFormat('dd MMM yyyy');
    final accent = PdfColor.fromHex('#FF5722');
    final dark = PdfColor.fromHex('#1A1D24');
    final muted = PdfColor.fromHex('#64748B');
    final border = PdfColor.fromHex('#E2E8F0');

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(34),
        footer: (context) => pw.Container(
          padding: const pw.EdgeInsets.only(top: 10),
          decoration: pw.BoxDecoration(
            border: pw.Border(top: pw.BorderSide(color: border)),
          ),
          child: pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text(
                'Generated by GrillPOS',
                style: pw.TextStyle(color: muted, fontSize: 8),
              ),
              pw.Text(
                'Page ${context.pageNumber} of ${context.pagesCount}',
                style: pw.TextStyle(color: muted, fontSize: 8),
              ),
            ],
          ),
        ),
        build: (_) => [
          pw.Row(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Container(
                width: 46,
                height: 46,
                alignment: pw.Alignment.center,
                decoration: pw.BoxDecoration(
                  color: accent,
                  borderRadius: pw.BorderRadius.circular(10),
                ),
                child: pw.Text(
                  'GP',
                  style: pw.TextStyle(
                    color: PdfColors.white,
                    fontWeight: pw.FontWeight.bold,
                    fontSize: 17,
                  ),
                ),
              ),
              pw.SizedBox(width: 12),
              pw.Expanded(
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text(
                      businessName.isEmpty
                          ? 'GrillPOS Computer Center'
                          : businessName,
                      style: pw.TextStyle(
                        color: dark,
                        fontWeight: pw.FontWeight.bold,
                        fontSize: 19,
                      ),
                    ),
                    pw.SizedBox(height: 3),
                    pw.Text(
                      'Computer sales, service and warranty',
                      style: pw.TextStyle(color: muted, fontSize: 9),
                    ),
                  ],
                ),
              ),
              pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.end,
                children: [
                  pw.Text(
                    document.type.label.toUpperCase(),
                    style: pw.TextStyle(
                      color: accent,
                      fontWeight: pw.FontWeight.bold,
                      fontSize: 16,
                    ),
                  ),
                  pw.SizedBox(height: 3),
                  pw.Text(
                    document.documentNumber,
                    style: pw.TextStyle(
                      color: dark,
                      fontWeight: pw.FontWeight.bold,
                      fontSize: 10,
                    ),
                  ),
                ],
              ),
            ],
          ),
          pw.SizedBox(height: 24),
          pw.Container(
            padding: const pw.EdgeInsets.all(14),
            decoration: pw.BoxDecoration(
              color: PdfColor.fromHex('#F8FAFC'),
              borderRadius: pw.BorderRadius.circular(9),
              border: pw.Border.all(color: border),
            ),
            child: pw.Row(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Expanded(
                  child: _infoBlock(
                      'CUSTOMER',
                      [
                        document.customerName,
                        document.customerPhone,
                      ],
                      dark,
                      muted),
                ),
                pw.Expanded(
                  child: _infoBlock(
                      'DOCUMENT',
                      [
                        'Issued: ${date.format(document.createdAt)}',
                        if (document.expiryDate != null)
                          'Valid until: ${date.format(document.expiryDate!)}',
                        'Status: ${document.status.label}',
                      ],
                      dark,
                      muted),
                ),
              ],
            ),
          ),
          pw.SizedBox(height: 22),
          pw.Table(
            border: pw.TableBorder(
              horizontalInside: pw.BorderSide(color: border),
              bottom: pw.BorderSide(color: border),
            ),
            columnWidths: const {
              0: pw.FlexColumnWidth(3.8),
              1: pw.FlexColumnWidth(1),
              2: pw.FlexColumnWidth(1.5),
              3: pw.FlexColumnWidth(1.6),
            },
            children: [
              pw.TableRow(
                decoration: pw.BoxDecoration(color: dark),
                children: [
                  _tableCell('PRODUCT', header: true),
                  _tableCell('QTY', header: true, alignRight: true),
                  _tableCell('UNIT PRICE', header: true, alignRight: true),
                  _tableCell('TOTAL', header: true, alignRight: true),
                ],
              ),
              ...document.lines.map(
                (line) => pw.TableRow(
                  children: [
                    pw.Padding(
                      padding: const pw.EdgeInsets.symmetric(
                        horizontal: 8,
                        vertical: 9,
                      ),
                      child: pw.Column(
                        crossAxisAlignment: pw.CrossAxisAlignment.start,
                        children: [
                          pw.Text(
                            line.productName,
                            style: pw.TextStyle(
                              color: dark,
                              fontWeight: pw.FontWeight.bold,
                              fontSize: 9,
                            ),
                          ),
                          if (line.sku?.isNotEmpty ?? false)
                            pw.Text(
                              'SKU: ${line.sku}',
                              style: pw.TextStyle(color: muted, fontSize: 7.5),
                            ),
                          if (line.serials.isNotEmpty)
                            pw.Text(
                              'Serial: ${line.serials.map((s) => s.serialNumber).join(', ')}',
                              style: pw.TextStyle(color: muted, fontSize: 7.5),
                            ),
                          if (line.warrantyMonths > 0)
                            pw.Text(
                              'Warranty: ${line.warrantyMonths} months${line.warrantyExpiry == null ? '' : ' until ${date.format(line.warrantyExpiry!)}'}',
                              style: pw.TextStyle(color: accent, fontSize: 7.5),
                            ),
                        ],
                      ),
                    ),
                    _tableCell(_quantity(line.quantity), alignRight: true),
                    _tableCell(money(line.unitPrice), alignRight: true),
                    _tableCell(money(line.lineSubtotal), alignRight: true),
                  ],
                ),
              ),
            ],
          ),
          pw.SizedBox(height: 18),
          pw.Row(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Expanded(
                flex: 3,
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    if (document.notes?.trim().isNotEmpty ?? false) ...[
                      pw.Text(
                        'NOTES',
                        style: pw.TextStyle(
                          color: muted,
                          fontWeight: pw.FontWeight.bold,
                          fontSize: 8,
                        ),
                      ),
                      pw.SizedBox(height: 5),
                      pw.Text(
                        document.notes!,
                        style: pw.TextStyle(color: dark, fontSize: 9),
                      ),
                    ],
                  ],
                ),
              ),
              pw.SizedBox(width: 28),
              pw.Expanded(
                flex: 2,
                child: pw.Column(
                  children: [
                    _totalRow('Subtotal', money(document.subtotal), muted),
                    if (document.discountAmount > 0)
                      _totalRow(
                        'Discount',
                        '-${money(document.discountAmount)}',
                        muted,
                      ),
                    if (document.taxAmount > 0)
                      _totalRow(
                        'Tax (${document.taxRate.toStringAsFixed(1)}%)',
                        money(document.taxAmount),
                        muted,
                      ),
                    pw.Divider(color: border),
                    _totalRow(
                      'TOTAL',
                      money(document.totalAmount),
                      dark,
                      bold: true,
                    ),
                    if (document.type == ComputerDocumentType.sale) ...[
                      _totalRow(
                        'Paid',
                        money(document.paidAmount),
                        muted,
                      ),
                      _totalRow(
                        'Balance due',
                        money(document.balanceDue),
                        document.balanceDue > 0 ? accent : muted,
                        bold: document.balanceDue > 0,
                      ),
                    ],
                  ],
                ),
              ),
            ],
          ),
          if (document.type == ComputerDocumentType.sale &&
              document.lines.any((line) => line.warrantyMonths > 0)) ...[
            pw.SizedBox(height: 28),
            pw.Container(
              width: double.infinity,
              padding: const pw.EdgeInsets.all(14),
              decoration: pw.BoxDecoration(
                border: pw.Border.all(color: accent, width: .8),
                borderRadius: pw.BorderRadius.circular(9),
              ),
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text(
                    'WARRANTY CERTIFICATE',
                    style: pw.TextStyle(
                      color: accent,
                      fontWeight: pw.FontWeight.bold,
                      fontSize: 11,
                    ),
                  ),
                  pw.SizedBox(height: 6),
                  pw.Text(
                    'This document confirms the warranty periods and serial numbers listed above. Warranty applies to manufacturing defects and excludes misuse, physical damage, liquid damage, and unauthorized repair.',
                    style: pw.TextStyle(
                        color: dark, fontSize: 8.5, lineSpacing: 2),
                  ),
                ],
              ),
            ),
          ],
          pw.SizedBox(height: 32),
          pw.Row(
            children: [
              pw.Expanded(
                  child: _signature('Customer signature', border, muted)),
              pw.SizedBox(width: 40),
              pw.Expanded(
                  child: _signature('Authorized signature', border, muted)),
            ],
          ),
        ],
      ),
    );
    return pdf.save();
  }

  static pw.Widget _infoBlock(
    String title,
    List<String> values,
    PdfColor dark,
    PdfColor muted,
  ) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          title,
          style: pw.TextStyle(
            color: muted,
            fontWeight: pw.FontWeight.bold,
            fontSize: 7.5,
          ),
        ),
        pw.SizedBox(height: 5),
        for (var index = 0; index < values.length; index++)
          pw.Text(
            values[index],
            style: pw.TextStyle(
              color: dark,
              fontWeight:
                  index == 0 ? pw.FontWeight.bold : pw.FontWeight.normal,
              fontSize: index == 0 ? 10 : 8.5,
            ),
          ),
      ],
    );
  }

  static pw.Widget _tableCell(
    String text, {
    bool header = false,
    bool alignRight = false,
  }) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 9),
      child: pw.Text(
        text,
        textAlign: alignRight ? pw.TextAlign.right : pw.TextAlign.left,
        style: pw.TextStyle(
          color: header ? PdfColors.white : PdfColor.fromHex('#1A1D24'),
          fontWeight: header ? pw.FontWeight.bold : pw.FontWeight.normal,
          fontSize: header ? 7.5 : 9,
        ),
      ),
    );
  }

  static pw.Widget _totalRow(
    String label,
    String value,
    PdfColor color, {
    bool bold = false,
  }) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 3),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(
            label,
            style: pw.TextStyle(
              color: color,
              fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal,
              fontSize: bold ? 10 : 8.5,
            ),
          ),
          pw.Text(
            value,
            style: pw.TextStyle(
              color: color,
              fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal,
              fontSize: bold ? 10 : 8.5,
            ),
          ),
        ],
      ),
    );
  }

  static pw.Widget _signature(
    String label,
    PdfColor border,
    PdfColor muted,
  ) {
    return pw.Column(
      children: [
        pw.Container(height: 26),
        pw.Divider(color: border),
        pw.Text(label, style: pw.TextStyle(color: muted, fontSize: 8)),
      ],
    );
  }

  static String _quantity(double value) => value == value.roundToDouble()
      ? value.toInt().toString()
      : value.toStringAsFixed(2);
}
